### ISSUE TITLE
SIGSEGV thrown randomly 

### ISSUE THREAD

**Issue by phoinixgrr** [mattermost/mattermost-mattermod#328]
Jobserver component seems to randomly throw segmentation fault: 

```
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver panic: runtime error: invalid memory address or nil pointer dereference
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xca36f6]
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver goroutine 215760 [running]:
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver github.com/mattermost/mattermost-mattermod/server.(*Server).Tick(0xc0000e6c60)
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver 	/go/src/mattermod/server/server.go:221 +0x696
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver github.com/robfig/cron/v3.FuncJob.Run(0xc00044a320)
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver 	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1a
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver github.com/robfig/cron/v3.(*Cron).startJob.func1()
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver 	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver created by github.com/robfig/cron/v3.(*Cron).startJob
mattermod-jobserver-7b96f6fc58-9ghbx:mattermod-jobserver 	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xb2
```

**Comment by phoinixgrr** [comment]
Fixes with https://github.com/mattermost/mattermost-mattermod/pull/329
